### ISSUE TITLE
Code/Data

### ISSUE THREAD

**Issue by Gautamshahi** [ICTMCG/FTT-ACL23#1]
Hi,

There are no files uploaded in the repository. Is it going to be available soon?

**Comment by JieWu02** [comment]
There are no files uploaded in the repository. Is it going to be available soon? Thank you！

**Comment by Gautamshahi** [comment]
Dear Authors, are you willing to share code or data?

**Comment by beanandrew** [comment]
Thank you for your attention, we have released our code and sample data.
